name: 'Remark Action'
description: 'Validate Markdown with remark.'
author: 'ocular-d'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  check_dir:
    description: 'Name of the directory remark should check'
    required: true
    default: 'docs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.check_dir }}
