on: push
name: New workflow
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      uses: ./
      with:
        folder-path: 'md'
