on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ./
      with:
        folder-path: 'md'

    - name: Display status from remark
      run: echo "${{ steps.remark.outputs.status }}"
