on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ./
      with:
        folder-path: 'md'

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Result: 
          ${{ steps.remark.outputs.status }}
