on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ./
      with:
        folder-path: 'md'

    - name: Create Issue
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Report
        content-filepath: error.log
        labels: report, automated issue

    - name: Fail if there were link errors
      run: exit ${{ steps.remark.outputs.exit_code }}

