on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ./
      with:
        check-dir: 'md'
