on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ./
      with:
        check-dir: 'md'
    - name: Create Issue
      if: ${{ steps.remark.outputs.exit_code }}
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Report
        content-filepath: error.log
        labels: report, automated issue
